services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: mariadb:latest
    pull_policy: build
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      app-net:
        aliases:
          - db.local

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
#    container_name: web
    restart: always
    depends_on:
      db:
        condition: service_started
    env_file:
      - .env
    environment:
      MYSQL_HOST: db.local
    ports:
      - "5000:5000"
    networks:
      - app-net
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]  # Adjust the port/path as needed
#    image: python:3.11-slim
    pull_policy: build

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    pull_policy: build
#    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - web
#        condition: service_healthy
    restart: on-failure
    networks:
      - app-net
    labels:
      shipyard.route: "/"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db_data:

networks:
  app-net:
